version: '3'

services:
  db:
    image: mysql:5.7
    container_name: wordpress-db-container
    volumes:
      - ./volumes/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  
  wordpress:
    container_name: wordpress-container
    depends_on:
      - db
    build: ./wordpress    
    volumes:
      - ./volumes/wordpress_themes:/var/www/html/wp-content/themes
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  
  composer:
    container_name: composer
    image: composer
    command: "composer install"
    volumes:
      - ./volumes/composer:/app
      - ./volumes/wordpress_themes:/code
